const fs = require("fs");
const path = require("path");
const dir = path.join("src", "content", "quizzes");
const src = [
  { citation: "Miller Center: U.S. Presidents", url: "https://millercenter.org/president", publisher: "Miller Center, University of Virginia", tier: 1, accessedDate: "2026-04-20" },
  { citation: "National Park Service", url: "https://www.nps.gov/subjects/americanhistory/index.htm", publisher: "National Park Service", tier: 1, accessedDate: "2026-04-20" }
];

function dv(s, e) { return { scholar: s, explorer: e }; }
function opt(s, e) { return { scholar: s, explorer: e || s }; }

function writeQ(q) {
  fs.writeFileSync(path.join(dir, q.id + ".json"), JSON.stringify(q, null, 2));
}

// ═══ QUIZ 1: Presidents Basics ═══
const q1 = [];
q1.push({ id:"q-pres-1", status:"published", topic:"presidents", difficulty:"easy", mode:"both", prompt: dv("Who was the first President of the United States?","Who was the very first President of the United States?"), options:[opt("John Adams"),opt("George Washington"),opt("Thomas Jefferson"),opt("Benjamin Franklin")], correctIndex:1, explanation:dv("George Washington served as the first President from 1789 to 1797. He is known as the 'Father of His Country.'","George Washington was the very first president! He led the country from 1789 to 1797."), sources:src });
q1.push({ id:"q-pres-2", status:"published", topic:"presidents", difficulty:"easy", mode:"both", prompt: dv("Which president wrote the Declaration of Independence?","Which president WROTE the Declaration of Independence?"), options:[opt("George Washington"),opt("John Adams"),opt("Thomas Jefferson"),opt("James Madison")], correctIndex:2, explanation:dv("Thomas Jefferson authored the Declaration of Independence in 1776, articulating the principle that 'all men are created equal.'","Thomas Jefferson wrote the Declaration of Independence in 1776!"), sources:src });
q1.push({ id:"q-pres-3", status:"published", topic:"presidents", difficulty:"easy", mode:"both", prompt: dv("Which president is known as the 'Father of the Constitution'?","Which president is called the 'Father of the Constitution'?"), options:[opt("Thomas Jefferson"),opt("Alexander Hamilton"),opt("James Madison"),opt("George Washington")], correctIndex:2, explanation:dv("James Madison played the foremost role in drafting the Constitution at the 1787 Convention.","James Madison did more than anyone else to write the Constitution!"), sources:src });
q1.push({ id:"q-pres-4", status:"published", topic:"presidents", difficulty:"medium", mode:"both", prompt: dv("Which president served the shortest term in office?","Which president was president for the LEAST amount of time?"), options:[opt("James A. Garfield"),opt("William Henry Harrison"),opt("Zachary Taylor"),opt("John Tyler")], correctIndex:1, explanation:dv("William Henry Harrison served only 32 days before dying in office — the shortest presidential tenure in history.","William Henry Harrison was only president for 32 days — the shortest ever!"), sources:src });
q1.push({ id:"q-pres-5", status:"published", topic:"presidents", difficulty:"easy", mode:"both", prompt: dv("Who was the first African American president?","Who was the first Black president of the United States?"), options:[opt("Joe Biden"),opt("Bill Clinton"),opt("Barack Obama"),opt("Donald Trump")], correctIndex:2, explanation:dv("Barack Obama was elected the 44th President in 2008, becoming the first African American to hold the office.","Barack Obama made history in 2008 as the first Black president!"), sources:src });
q1.push({ id:"q-pres-6", status:"published", topic:"presidents", difficulty:"medium", mode:"both", prompt: dv("Which president issued the Emancipation Proclamation?","Which president freed the enslaved people with the Emancipation Proclamation?"), options:[opt("Ulysses S. Grant"),opt("Andrew Johnson"),opt("Abraham Lincoln"),opt("George Washington")], correctIndex:2, explanation:dv("Abraham Lincoln issued the Emancipation Proclamation on January 1, 1863, freeing enslaved people in Confederate states.","Abraham Lincoln signed the Emancipation Proclamation in 1863!"), sources:src });
q1.push({ id:"q-pres-7", status:"published", topic:"presidents", difficulty:"medium", mode:"both", prompt: dv("Which president created the New Deal?","Which president started the New Deal to help people during the Great Depression?"), options:[opt("Herbert Hoover"),opt("Harry Truman"),opt("Franklin D. Roosevelt"),opt("Dwight Eisenhower")], correctIndex:2, explanation:dv("FDR launched the New Deal beginning in 1933, creating programs to provide relief during the Great Depression.","FDR created the New Deal to give people jobs and help during the Great Depression!"), sources:src });
q1.push({ id:"q-pres-8", status:"published", topic:"presidents", difficulty:"hard", mode:"both", prompt: dv("Which president is the only one to serve two non-consecutive terms (besides Trump)?","Before Trump, which president left the White House and then came back for a second time?"), options:[opt("Theodore Roosevelt"),opt("Grover Cleveland"),opt("Andrew Jackson"),opt("John Adams")], correctIndex:1, explanation:dv("Grover Cleveland served as both the 22nd and 24th President, the first to serve non-consecutive terms.","Grover Cleveland was president #22 AND #24 — the first person to leave and come back!"), sources:src });
q1.push({ id:"q-pres-9", status:"published", topic:"presidents", difficulty:"medium", mode:"both", prompt: dv("Which president established the Peace Corps?","Which president created the Peace Corps to send volunteers around the world?"), options:[opt("Lyndon Johnson"),opt("John F. Kennedy"),opt("Richard Nixon"),opt("Jimmy Carter")], correctIndex:1, explanation:dv("JFK established the Peace Corps by executive order on March 1, 1961.","JFK created the Peace Corps in 1961!"), sources:src });
q1.push({ id:"q-pres-10", status:"published", topic:"presidents", difficulty:"hard", mode:"both", prompt: dv("Which president was the only one to also serve as Chief Justice of the Supreme Court?","Which president also became the top judge on the Supreme Court?"), options:[opt("John Adams"),opt("William Howard Taft"),opt("Thomas Jefferson"),opt("John Marshall")], correctIndex:1, explanation:dv("Taft served as the 27th President and was later appointed Chief Justice in 1921 — the only person to hold both offices.","William Howard Taft is the only person who was BOTH president AND Chief Justice!"), sources:src });

// ═══ QUIZ 2: Major Events ═══
const q2 = [];
q2.push({ id:"q-event-1", status:"published", topic:"general", difficulty:"easy", mode:"both", prompt: dv("In what year was the Declaration of Independence signed?","When did America declare independence?"), options:[opt("1774"),opt("1776"),opt("1778"),opt("1781")], correctIndex:1, explanation:dv("The Declaration of Independence was adopted by the Continental Congress on July 4, 1776.","The Declaration of Independence was signed on July 4, 1776 — that's why we celebrate the Fourth of July!"), sources:src });
q2.push({ id:"q-event-2", status:"published", topic:"wars", difficulty:"easy", mode:"both", prompt: dv("What event triggered the United States' entry into World War II?","What attack made America join World War II?"), options:[opt("Sinking of the Lusitania"),opt("D-Day invasion"),opt("Attack on Pearl Harbor"),opt("Battle of the Bulge")], correctIndex:2, explanation:dv("Japan's attack on Pearl Harbor on December 7, 1941 brought the United States into World War II.","Japan's surprise attack on Pearl Harbor on December 7, 1941 brought America into the war!"), sources:src });
q2.push({ id:"q-event-3", status:"published", topic:"general", difficulty:"medium", mode:"both", prompt: dv("What did the Louisiana Purchase accomplish in 1803?","What happened with the Louisiana Purchase?"), options:[opt("Ended the War of 1812"),opt("Doubled the size of the United States"),opt("Freed enslaved people"),opt("Created the Constitution")], correctIndex:1, explanation:dv("The Louisiana Purchase from France doubled the size of the United States, adding approximately 828,000 square miles.","The Louisiana Purchase doubled the size of America — President Jefferson bought it from France for just 4 cents an acre!"), sources:src });
q2.push({ id:"q-event-4", status:"published", topic:"civil-rights", difficulty:"easy", mode:"both", prompt: dv("Who refused to give up her bus seat in Montgomery, Alabama in 1955?","Who was the brave woman who wouldn't give up her bus seat?"), options:[opt("Harriet Tubman"),opt("Susan B. Anthony"),opt("Rosa Parks"),opt("Eleanor Roosevelt")], correctIndex:2, explanation:dv("Rosa Parks' arrest on December 1, 1955 sparked the Montgomery Bus Boycott, a key event in the civil rights movement.","Rosa Parks refused to give up her seat on December 1, 1955, starting a 381-day bus boycott!"), sources:src });
q2.push({ id:"q-event-5", status:"published", topic:"general", difficulty:"medium", mode:"both", prompt: dv("What was the significance of the Battle of Gettysburg (1863)?","Why was the Battle of Gettysburg so important?"), options:[opt("It started the Civil War"),opt("It was the turning point of the Civil War"),opt("It ended the Civil War"),opt("It freed the enslaved people")], correctIndex:1, explanation:dv("Gettysburg (July 1-4, 1863) is widely regarded as the turning point of the Civil War, with 51,116 casualties.","Gettysburg was the turning point — after this battle, the Union started winning the war!"), sources:src });
q2.push({ id:"q-event-6", status:"published", topic:"general", difficulty:"easy", mode:"both", prompt: dv("Who was the first person to walk on the Moon?","Who was the first human to walk on the Moon?"), options:[opt("Buzz Aldrin"),opt("John Glenn"),opt("Neil Armstrong"),opt("Alan Shepard")], correctIndex:2, explanation:dv("Neil Armstrong became the first human to walk on the Moon on July 20, 1969, during the Apollo 11 mission.","Neil Armstrong walked on the Moon on July 20, 1969!"), sources:src });
q2.push({ id:"q-event-7", status:"published", topic:"general", difficulty:"medium", mode:"both", prompt: dv("What scandal forced President Nixon to resign in 1974?","What scandal made President Nixon quit?"), options:[opt("Iran-Contra"),opt("Teapot Dome"),opt("Watergate"),opt("Monica Lewinsky")], correctIndex:2, explanation:dv("The Watergate scandal, involving a break-in cover-up, made Nixon the only president to resign, on August 9, 1974.","The Watergate scandal was about Nixon trying to cover up a break-in. He's the only president who ever quit!"), sources:src });
q2.push({ id:"q-event-8", status:"published", topic:"wars", difficulty:"medium", mode:"both", prompt: dv("What date is known as D-Day?","When was D-Day — the huge invasion of Normandy?"), options:[opt("December 7, 1941"),opt("June 6, 1944"),opt("August 6, 1945"),opt("May 8, 1945")], correctIndex:1, explanation:dv("D-Day was June 6, 1944, when approximately 156,000 Allied troops stormed the beaches of Normandy, France.","D-Day was June 6, 1944 — about 156,000 soldiers crossed the ocean and stormed the beaches to fight the Nazis!"), sources:src });
q2.push({ id:"q-event-9", status:"published", topic:"general", difficulty:"hard", mode:"both", prompt: dv("What was the Sherman Antitrust Act (1890) designed to do?","What did the Sherman Antitrust Act do?"), options:[opt("End slavery"),opt("Prohibit monopolies"),opt("Create national parks"),opt("Establish income tax")], correctIndex:1, explanation:dv("The Sherman Antitrust Act of 1890 was the first federal law to prohibit monopolies and anticompetitive business practices.","The Sherman Antitrust Act said giant companies couldn't team up to control everything and charge unfair prices!"), sources:src });
q2.push({ id:"q-event-10", status:"published", topic:"general", difficulty:"medium", mode:"both", prompt: dv("What did the 19th Amendment (1920) accomplish?","What did the 19th Amendment do?"), options:[opt("Abolished slavery"),opt("Established Prohibition"),opt("Granted women the right to vote"),opt("Lowered the voting age")], correctIndex:2, explanation:dv("The 19th Amendment, ratified in 1920, granted women the right to vote after a 72-year struggle.","The 19th Amendment gave women the right to vote in 1920 — after fighting for it for 72 years!"), sources:src });

// ═══ QUIZ 3: Inventions ═══
const q3 = [];
q3.push({ id:"q-inv-1", status:"published", topic:"inventions", difficulty:"easy", mode:"both", prompt: dv("Who invented the practical electric light bulb?","Who invented the light bulb?"), options:[opt("Benjamin Franklin"),opt("Nikola Tesla"),opt("Thomas Edison"),opt("Alexander Graham Bell")], correctIndex:2, explanation:dv("Thomas Edison developed the first commercially practical incandescent light bulb in 1879.","Thomas Edison created the light bulb in 1879!"), sources:src });
q3.push({ id:"q-inv-2", status:"published", topic:"inventions", difficulty:"easy", mode:"both", prompt: dv("Who invented the telephone?","Who invented the telephone?"), options:[opt("Thomas Edison"),opt("Alexander Graham Bell"),opt("Samuel Morse"),opt("Nikola Tesla")], correctIndex:1, explanation:dv("Alexander Graham Bell patented the telephone in 1876.","Alexander Graham Bell invented the telephone in 1876!"), sources:src });
q3.push({ id:"q-inv-3", status:"published", topic:"inventions", difficulty:"medium", mode:"both", prompt: dv("What did Eli Whitney's cotton gin (1793) inadvertently cause?","What happened because of the cotton gin?"), options:[opt("The end of slavery"),opt("A dramatic increase in slavery"),opt("The Industrial Revolution"),opt("Westward expansion")], correctIndex:1, explanation:dv("The cotton gin made cotton enormously profitable, dramatically increasing demand for enslaved labor.","The cotton gin actually made slavery WORSE because plantation owners wanted even more enslaved people to grow cotton."), sources:src });
q3.push({ id:"q-inv-4", status:"published", topic:"inventions", difficulty:"easy", mode:"both", prompt: dv("Who achieved the first powered airplane flight?","Who flew the first airplane?"), options:[opt("Charles Lindbergh"),opt("Amelia Earhart"),opt("The Wright Brothers"),opt("Henry Ford")], correctIndex:2, explanation:dv("Orville and Wilbur Wright achieved the first powered flight on December 17, 1903.","The Wright Brothers flew the first airplane on December 17, 1903!"), sources:src });
q3.push({ id:"q-inv-5", status:"published", topic:"inventions", difficulty:"medium", mode:"both", prompt: dv("What did Henry Ford's assembly line (1913) accomplish?","What was special about Henry Ford's assembly line?"), options:[opt("Invented the automobile"),opt("Made cars affordable for ordinary people"),opt("Created the first truck"),opt("Built the first highway")], correctIndex:1, explanation:dv("Ford's assembly line reduced the Model T price from $850 to under $300, making cars affordable for ordinary Americans.","Ford's assembly line made cars so cheap that regular families could afford them!"), sources:src });
q3.push({ id:"q-inv-6", status:"published", topic:"inventions", difficulty:"medium", mode:"both", prompt: dv("What was the first message sent over the internet (ARPANET) in 1969?","What was the first internet message?"), options:[opt("Hello World"),opt("LO (the system crashed before completing LOGIN)"),opt("Testing 123"),opt("Can you hear me")], correctIndex:1, explanation:dv("The first ARPANET message was supposed to be 'LOGIN' but the system crashed after transmitting just 'LO.'","The first internet message was supposed to say LOGIN but the computer crashed after just two letters: LO!"), sources:src });
q3.push({ id:"q-inv-7", status:"published", topic:"inventions", difficulty:"easy", mode:"both", prompt: dv("What was completed at Promontory Summit, Utah in 1869?","What was connected at Promontory Summit, Utah in 1869?"), options:[opt("The Panama Canal"),opt("The Transcontinental Railroad"),opt("The Telegraph"),opt("The Erie Canal")], correctIndex:1, explanation:dv("The first transcontinental railroad was completed on May 10, 1869.","The first railroad that went across the WHOLE country was finished on May 10, 1869!"), sources:src });
q3.push({ id:"q-inv-8", status:"published", topic:"inventions", difficulty:"hard", mode:"both", prompt: dv("What did Samuel Morse demonstrate in 1844?","What did Samuel Morse show off in 1844?"), options:[opt("The telephone"),opt("The telegraph"),opt("The radio"),opt("The typewriter")], correctIndex:1, explanation:dv("Morse demonstrated the electromagnetic telegraph in 1844 with the message 'What hath God wrought.'","Morse sent the first telegraph message in 1844: 'What hath God wrought!'"), sources:src });
q3.push({ id:"q-inv-9", status:"published", topic:"inventions", difficulty:"medium", mode:"both", prompt: dv("Where was Apple Computer founded?","Where did Steve Jobs start Apple?"), options:[opt("A college dorm room"),opt("A garage in California"),opt("An office in New York"),opt("A lab in Massachusetts")], correctIndex:1, explanation:dv("Apple Computer was founded in Steve Jobs's parents' garage in Los Altos, California in 1976.","Apple started in a garage in California in 1976!"), sources:src });
q3.push({ id:"q-inv-10", status:"published", topic:"inventions", difficulty:"hard", mode:"both", prompt: dv("Who achieved the first controlled nuclear chain reaction in 1942?","Who created the first controlled nuclear reaction?"), options:[opt("Albert Einstein"),opt("Robert Oppenheimer"),opt("Enrico Fermi"),opt("Niels Bohr")], correctIndex:2, explanation:dv("Enrico Fermi achieved the first controlled nuclear chain reaction at the University of Chicago on December 2, 1942.","Enrico Fermi did it on December 2, 1942, under the bleachers of a football stadium at the University of Chicago!"), sources:src });

// ═══ QUIZ 4: Civil Rights ═══
const q4 = [];
q4.push({ id:"q-cr-1", status:"published", topic:"civil-rights", difficulty:"easy", mode:"both", prompt: dv("What did the 13th Amendment abolish?","What did the 13th Amendment end?"), options:[opt("Alcohol"),opt("Slavery"),opt("Poll taxes"),opt("Segregation")], correctIndex:1, explanation:dv("The 13th Amendment, ratified in 1865, abolished slavery throughout the United States.","The 13th Amendment ended slavery forever in 1865!"), sources:src });
q4.push({ id:"q-cr-2", status:"published", topic:"civil-rights", difficulty:"easy", mode:"both", prompt: dv("Who gave the 'I Have a Dream' speech?","Who gave the famous 'I Have a Dream' speech?"), options:[opt("Frederick Douglass"),opt("Malcolm X"),opt("Martin Luther King Jr."),opt("Barack Obama")], correctIndex:2, explanation:dv("MLK delivered the speech at the March on Washington on August 28, 1963.","Martin Luther King Jr. gave this famous speech at the March on Washington in 1963!"), sources:src });
q4.push({ id:"q-cr-3", status:"published", topic:"civil-rights", difficulty:"medium", mode:"both", prompt: dv("What did Brown v. Board of Education (1954) declare?","What did the Brown v. Board court case decide?"), options:[opt("Slavery was unconstitutional"),opt("Women could vote"),opt("School segregation was unconstitutional"),opt("The death penalty was wrong")], correctIndex:2, explanation:dv("The Supreme Court ruled that racial segregation in public schools was unconstitutional.","The Supreme Court said that separating kids by race in schools was unconstitutional — separate is NOT equal!"), sources:src });
q4.push({ id:"q-cr-4", status:"published", topic:"civil-rights", difficulty:"medium", mode:"both", prompt: dv("Who conducted passengers on the Underground Railroad?","Who helped enslaved people escape on the Underground Railroad?"), options:[opt("Sojourner Truth"),opt("Harriet Tubman"),opt("Frederick Douglass"),opt("Rosa Parks")], correctIndex:1, explanation:dv("Harriet Tubman made approximately 13 trips and guided around 70 people to freedom.","Harriet Tubman made about 13 trips and helped around 70 people escape to freedom!"), sources:src });
q4.push({ id:"q-cr-5", status:"published", topic:"civil-rights", difficulty:"easy", mode:"both", prompt: dv("Who broke baseball's color barrier in 1947?","Who was the first Black player in Major League Baseball?"), options:[opt("Hank Aaron"),opt("Willie Mays"),opt("Satchel Paige"),opt("Jackie Robinson")], correctIndex:3, explanation:dv("Jackie Robinson took the field for the Brooklyn Dodgers on April 15, 1947.","Jackie Robinson played his first game for the Brooklyn Dodgers on April 15, 1947!"), sources:src });
q4.push({ id:"q-cr-6", status:"published", topic:"civil-rights", difficulty:"medium", mode:"both", prompt: dv("When did women gain the right to vote in the United States?","When did American women get the right to vote?"), options:[opt("1865"),opt("1900"),opt("1920"),opt("1945")], correctIndex:2, explanation:dv("The 19th Amendment was ratified on August 18, 1920, granting women the right to vote.","Women got the right to vote in 1920 with the 19th Amendment!"), sources:src });
q4.push({ id:"q-cr-7", status:"published", topic:"civil-rights", difficulty:"hard", mode:"both", prompt: dv("What was the Seneca Falls Convention (1848)?","What happened at Seneca Falls in 1848?"), options:[opt("A Civil War battle"),opt("The first women's rights convention"),opt("A presidential debate"),opt("An abolition rally")], correctIndex:1, explanation:dv("Seneca Falls was the first women's rights convention in American history, launching the suffrage movement.","Seneca Falls was the very first meeting where women demanded equal rights!"), sources:src });
q4.push({ id:"q-cr-8", status:"published", topic:"civil-rights", difficulty:"medium", mode:"both", prompt: dv("What did the Civil Rights Act of 1964 prohibit?","What did the Civil Rights Act of 1964 make illegal?"), options:[opt("Gun ownership"),opt("Discrimination based on race, color, religion, sex, or national origin"),opt("Immigration from certain countries"),opt("Protests in public spaces")], correctIndex:1, explanation:dv("The act prohibited discrimination in employment, public accommodations, and federally funded programs.","The Civil Rights Act made it illegal to treat people unfairly because of their race, religion, or gender!"), sources:src });
q4.push({ id:"q-cr-9", status:"published", topic:"civil-rights", difficulty:"easy", mode:"both", prompt: dv("What did Frederick Douglass escape from to become a leading abolitionist?","What did Frederick Douglass escape from?"), options:[opt("Prison"),opt("The military"),opt("Slavery"),opt("Poverty")], correctIndex:2, explanation:dv("Douglass escaped slavery and became the most prominent African American voice of the 19th century.","Frederick Douglass escaped from slavery and became one of the most powerful speakers against it!"), sources:src });
q4.push({ id:"q-cr-10", status:"published", topic:"civil-rights", difficulty:"hard", mode:"both", prompt: dv("What did the Voting Rights Act of 1965 specifically target?","What unfair things did the Voting Rights Act of 1965 get rid of?"), options:[opt("Poll taxes only"),opt("Barriers preventing African Americans from voting, especially literacy tests"),opt("Age restrictions on voting"),opt("Property requirements for voting")], correctIndex:1, explanation:dv("The act banned literacy tests and authorized federal oversight in areas with histories of voter discrimination.","It got rid of unfair tests and rules that had been used to stop Black people from voting!"), sources:src });

// ═══ QUIZ 5: Wars ═══
const q5 = [];
q5.push({ id:"q-war-1", status:"published", topic:"wars", difficulty:"easy", mode:"both", prompt: dv("What war was fought between the North and South of the United States?","What was the war between the North and South called?"), options:[opt("Revolutionary War"),opt("War of 1812"),opt("Civil War"),opt("Mexican-American War")], correctIndex:2, explanation:dv("The American Civil War (1861-1865) was fought between Union and Confederate forces over slavery and states' rights.","The Civil War was fought from 1861 to 1865 between the North (Union) and South (Confederacy)."), sources:src });
q5.push({ id:"q-war-2", status:"published", topic:"wars", difficulty:"medium", mode:"both", prompt: dv("What was the turning point of the American Revolution?","Which battle changed everything in the Revolutionary War?"), options:[opt("Battle of Bunker Hill"),opt("Battle of Saratoga"),opt("Battle of Yorktown"),opt("Battle of Trenton")], correctIndex:1, explanation:dv("The Battle of Saratoga (1777) convinced France to ally with America, transforming the war.","The Battle of Saratoga convinced France to help America — that changed everything!"), sources:src });
q5.push({ id:"q-war-3", status:"published", topic:"wars", difficulty:"easy", mode:"both", prompt: dv("What ended World War II in the Pacific?","What ended the war with Japan?"), options:[opt("D-Day invasion"),opt("Battle of Midway"),opt("Atomic bombs on Hiroshima and Nagasaki"),opt("Invasion of Japan")], correctIndex:2, explanation:dv("The atomic bombings of Hiroshima (Aug 6) and Nagasaki (Aug 9), 1945 led to Japan's surrender.","The atomic bombs dropped on Hiroshima and Nagasaki in August 1945 led Japan to surrender."), sources:src });
q5.push({ id:"q-war-4", status:"published", topic:"wars", difficulty:"medium", mode:"both", prompt: dv("How many Americans died in the Civil War?","About how many Americans died in the Civil War?"), options:[opt("About 100,000"),opt("About 300,000"),opt("About 600,000"),opt("About 1 million")], correctIndex:2, explanation:dv("The Civil War resulted in over 600,000 American deaths — more than all other U.S. wars combined up to that point.","Over 600,000 Americans died — more than in all other American wars combined at that time!"), sources:src });
q5.push({ id:"q-war-5", status:"published", topic:"wars", difficulty:"easy", mode:"both", prompt: dv("What event symbolized the end of the Cold War?","What happened that showed the Cold War was ending?"), options:[opt("Moon landing"),opt("Fall of the Berlin Wall"),opt("Cuban Missile Crisis"),opt("Vietnam War ending")], correctIndex:1, explanation:dv("The Berlin Wall fell on November 9, 1989, symbolizing the collapse of Communist control in Eastern Europe.","The Berlin Wall came down on November 9, 1989!"), sources:src });
q5.push({ id:"q-war-6", status:"published", topic:"wars", difficulty:"medium", mode:"both", prompt: dv("What conflict did the United States enter after the September 11 attacks?","What did America do after 9/11?"), options:[opt("The Vietnam War"),opt("The Korean War"),opt("The War on Terror"),opt("The Gulf War")], correctIndex:2, explanation:dv("The September 11 attacks led to the War on Terror, including operations in Afghanistan and Iraq.","After 9/11, America started the War on Terror, sending troops to Afghanistan and Iraq."), sources:src });
q5.push({ id:"q-war-7", status:"published", topic:"wars", difficulty:"hard", mode:"both", prompt: dv("What did the Treaty of Paris (1783) accomplish?","What did the Treaty of Paris do in 1783?"), options:[opt("Ended the Civil War"),opt("Ended the War of 1812"),opt("Ended the Revolutionary War and recognized American independence"),opt("Ended World War I")], correctIndex:2, explanation:dv("The Treaty of Paris officially ended the Revolutionary War and recognized U.S. independence.","The Treaty of Paris ended the Revolutionary War — Britain finally said America was free!"), sources:src });
q5.push({ id:"q-war-8", status:"published", topic:"wars", difficulty:"medium", mode:"both", prompt: dv("What was D-Day (June 6, 1944)?","What happened on D-Day?"), options:[opt("Japan attacked Pearl Harbor"),opt("Germany surrendered"),opt("Allied forces invaded Normandy, France"),opt("The atomic bomb was dropped")], correctIndex:2, explanation:dv("About 156,000 Allied troops stormed the beaches of Normandy in the largest amphibious invasion in history.","About 156,000 soldiers landed on the beaches of France to start freeing Europe from the Nazis!"), sources:src });
q5.push({ id:"q-war-9", status:"published", topic:"wars", difficulty:"hard", mode:"both", prompt: dv("What crisis brought the world closest to nuclear war?","When was the world closest to a nuclear war?"), options:[opt("Korean War"),opt("Bay of Pigs"),opt("Cuban Missile Crisis"),opt("Vietnam War")], correctIndex:2, explanation:dv("The Cuban Missile Crisis (October 1962) is considered the closest the Cold War came to nuclear conflict.","The Cuban Missile Crisis in 1962 was the scariest moment of the Cold War — the world almost had a nuclear war!"), sources:src });
q5.push({ id:"q-war-10", status:"published", topic:"wars", difficulty:"easy", mode:"both", prompt: dv("Where did Confederate General Lee surrender to end the Civil War?","Where did the Civil War end?"), options:[opt("Gettysburg"),opt("Richmond"),opt("Appomattox Court House"),opt("Fort Sumter")], correctIndex:2, explanation:dv("Lee surrendered to Grant at Appomattox Court House, Virginia on April 9, 1865.","General Lee surrendered at Appomattox Court House in Virginia on April 9, 1865!"), sources:src });

// Write all questions
[...q1,...q2,...q3,...q4,...q5].forEach(q => writeQ(q));

// Write quiz definitions
const quizDefs = [
  { id:"quiz-presidents", status:"published", title:dv("Presidential Knowledge","How Well Do You Know the Presidents?"), description:dv("Test your knowledge of the 47 men who have led the nation.","See how much you know about America's presidents!"), topic:"presidents", difficulty:"medium", questionIds:q1.map(q=>q.id) },
  { id:"quiz-major-events", status:"published", title:dv("Major Events in American History","Big Moments in History!"), description:dv("From the Revolution to the modern era — how well do you know the pivotal moments?","Can you remember the biggest moments in American history?"), topic:"general", difficulty:"medium", questionIds:q2.map(q=>q.id) },
  { id:"quiz-inventions", status:"published", title:dv("American Inventions","Cool American Inventions!"), description:dv("Test your knowledge of the innovations that changed the world.","How much do you know about amazing American inventions?"), topic:"inventions", difficulty:"medium", questionIds:q3.map(q=>q.id) },
  { id:"quiz-civil-rights", status:"published", title:dv("The Fight for Equal Rights","Heroes of Equal Rights!"), description:dv("From abolition to modern civil rights — test your knowledge of the struggle for equality.","How much do you know about the brave people who fought for equal rights?"), topic:"civil-rights", difficulty:"medium", questionIds:q4.map(q=>q.id) },
  { id:"quiz-wars", status:"published", title:dv("Wars & Conflicts","Wars and Battles!"), description:dv("From the Revolution to the War on Terror — test your knowledge of American military history.","How much do you know about the wars America has fought?"), topic:"wars", difficulty:"medium", questionIds:q5.map(q=>q.id) },
];
quizDefs.forEach(q => writeQ(q));

console.log(`${[...q1,...q2,...q3,...q4,...q5].length} questions + ${quizDefs.length} quizzes written`);
